// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: notification_service.proto

package notification

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateRequest) Reset() {
	*x = GetTemplateRequest{}
	mi := &file_notification_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateRequest) ProtoMessage() {}

func (x *GetTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateRequest.ProtoReflect.Descriptor instead.
func (*GetTemplateRequest) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetTemplateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_notification_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListTemplatesResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Templates     []*NotificationTemplate `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesResponse) Reset() {
	*x = ListTemplatesResponse{}
	mi := &file_notification_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesResponse) ProtoMessage() {}

func (x *ListTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListTemplatesResponse) GetTemplates() []*NotificationTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

type ScheduleNotificationRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	TemplateId    int64                      `protobuf:"varint,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Recipients    []string                   `protobuf:"bytes,2,rep,name=recipients,proto3" json:"recipients,omitempty"`
	DynamicData   map[string]*structpb.Value `protobuf:"bytes,3,rep,name=dynamic_data,json=dynamicData,proto3" json:"dynamic_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ScheduleAt    *timestamppb.Timestamp     `protobuf:"bytes,4,opt,name=schedule_at,json=scheduleAt,proto3" json:"schedule_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleNotificationRequest) Reset() {
	*x = ScheduleNotificationRequest{}
	mi := &file_notification_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleNotificationRequest) ProtoMessage() {}

func (x *ScheduleNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleNotificationRequest.ProtoReflect.Descriptor instead.
func (*ScheduleNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_rawDescGZIP(), []int{3}
}

func (x *ScheduleNotificationRequest) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *ScheduleNotificationRequest) GetRecipients() []string {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *ScheduleNotificationRequest) GetDynamicData() map[string]*structpb.Value {
	if x != nil {
		return x.DynamicData
	}
	return nil
}

func (x *ScheduleNotificationRequest) GetScheduleAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduleAt
	}
	return nil
}

type ListDueScheduledRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Now           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=now,proto3" json:"now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDueScheduledRequest) Reset() {
	*x = ListDueScheduledRequest{}
	mi := &file_notification_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDueScheduledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDueScheduledRequest) ProtoMessage() {}

func (x *ListDueScheduledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDueScheduledRequest.ProtoReflect.Descriptor instead.
func (*ListDueScheduledRequest) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListDueScheduledRequest) GetNow() *timestamppb.Timestamp {
	if x != nil {
		return x.Now
	}
	return nil
}

type ListScheduledNotificationsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Notifications []*ScheduledNotification `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScheduledNotificationsResponse) Reset() {
	*x = ListScheduledNotificationsResponse{}
	mi := &file_notification_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScheduledNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScheduledNotificationsResponse) ProtoMessage() {}

func (x *ListScheduledNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScheduledNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListScheduledNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListScheduledNotificationsResponse) GetNotifications() []*ScheduledNotification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type MarkScheduledRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkScheduledRequest) Reset() {
	*x = MarkScheduledRequest{}
	mi := &file_notification_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkScheduledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkScheduledRequest) ProtoMessage() {}

func (x *MarkScheduledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkScheduledRequest.ProtoReflect.Descriptor instead.
func (*MarkScheduledRequest) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_rawDescGZIP(), []int{6}
}

func (x *MarkScheduledRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MarkScheduledRequest) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

type SendNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            []string               `protobuf:"bytes,1,rep,name=to,proto3" json:"to,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_notification_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_rawDescGZIP(), []int{7}
}

func (x *SendNotificationRequest) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SendNotificationRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendNotificationRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type SendNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationResponse) Reset() {
	*x = SendNotificationResponse{}
	mi := &file_notification_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationResponse) ProtoMessage() {}

func (x *SendNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendNotificationResponse) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_rawDescGZIP(), []int{8}
}

func (x *SendNotificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendNotificationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendBatchNotificationRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Notifications []*SendNotificationRequest `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBatchNotificationRequest) Reset() {
	*x = SendBatchNotificationRequest{}
	mi := &file_notification_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBatchNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBatchNotificationRequest) ProtoMessage() {}

func (x *SendBatchNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBatchNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendBatchNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_rawDescGZIP(), []int{9}
}

func (x *SendBatchNotificationRequest) GetNotifications() []*SendNotificationRequest {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type SendBatchNotificationResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Results       []*SendNotificationResponse `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBatchNotificationResponse) Reset() {
	*x = SendBatchNotificationResponse{}
	mi := &file_notification_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBatchNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBatchNotificationResponse) ProtoMessage() {}

func (x *SendBatchNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBatchNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendBatchNotificationResponse) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_rawDescGZIP(), []int{10}
}

func (x *SendBatchNotificationResponse) GetResults() []*SendNotificationResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_notification_service_proto protoreflect.FileDescriptor

const file_notification_service_proto_rawDesc = "" +
	"\n" +
	"\x1anotification_service.proto\x12\fnotification\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x12notification.proto\x1a\x1cgoogle/api/annotations.proto\"$\n" +
	"\x12GetTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"Y\n" +
	"\x15ListTemplatesResponse\x12@\n" +
	"\ttemplates\x18\x01 \x03(\v2\".notification.NotificationTemplateR\ttemplates\"\xd2\x02\n" +
	"\x1bScheduleNotificationRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\x03R\n" +
	"templateId\x12\x1e\n" +
	"\n" +
	"recipients\x18\x02 \x03(\tR\n" +
	"recipients\x12]\n" +
	"\fdynamic_data\x18\x03 \x03(\v2:.notification.ScheduleNotificationRequest.DynamicDataEntryR\vdynamicData\x12;\n" +
	"\vschedule_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"scheduleAt\x1aV\n" +
	"\x10DynamicDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"G\n" +
	"\x17ListDueScheduledRequest\x12,\n" +
	"\x03now\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x03now\"o\n" +
	"\"ListScheduledNotificationsResponse\x12I\n" +
	"\rnotifications\x18\x01 \x03(\v2#.notification.ScheduledNotificationR\rnotifications\"[\n" +
	"\x14MarkScheduledRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x123\n" +
	"\asent_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\"W\n" +
	"\x17SendNotificationRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x03(\tR\x02to\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\"N\n" +
	"\x18SendNotificationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"k\n" +
	"\x1cSendBatchNotificationRequest\x12K\n" +
	"\rnotifications\x18\x01 \x03(\v2%.notification.SendNotificationRequestR\rnotifications\"a\n" +
	"\x1dSendBatchNotificationResponse\x12@\n" +
	"\aresults\x18\x01 \x03(\v2&.notification.SendNotificationResponseR\aresults2\xd7\n" +
	"\n" +
	"\x13NotificationService\x12r\n" +
	"\x0eCreateTemplate\x12\".notification.NotificationTemplate\x1a\".notification.NotificationTemplate\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/templates\x12o\n" +
	"\vGetTemplate\x12 .notification.GetTemplateRequest\x1a\".notification.NotificationTemplate\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/templates/{id}\x12c\n" +
	"\rListTemplates\x12\x16.google.protobuf.Empty\x1a#.notification.ListTemplatesResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/templates\x12k\n" +
	"\x0eUpdateTemplate\x12\".notification.NotificationTemplate\x1a\x16.google.protobuf.Empty\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/v1/templates/{id}\x12a\n" +
	"\x0eDeleteTemplate\x12\x1b.notification.DeleteRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/v1/templates/{id}\x12\x8d\x01\n" +
	"\x14ScheduleNotification\x12).notification.ScheduleNotificationRequest\x1a#.notification.ScheduledNotification\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/notifications/schedule\x12\x8a\x01\n" +
	"\x10ListDueScheduled\x12%.notification.ListDueScheduledRequest\x1a0.notification.ListScheduledNotificationsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/notifications/due\x12w\n" +
	"\x11MarkScheduledSent\x12\".notification.MarkScheduledRequest\x1a\x16.google.protobuf.Empty\"&\x82\xd3\xe4\x93\x02 :\x01*2\x1b/v1/notifications/{id}/sent\x12\x84\x01\n" +
	"\x10SendNotification\x12%.notification.SendNotificationRequest\x1a&.notification.SendNotificationResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/notifications/send\x12\x99\x01\n" +
	"\x15SendBatchNotification\x12*.notification.SendBatchNotificationRequest\x1a+.notification.SendBatchNotificationResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/notifications/send/batch\x12m\n" +
	"\aSendSMS\x12\x1c.notification.SendSMSRequest\x1a\x1d.notification.SendSMSResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/notifications/sms/sendBCZAgithub.com/armistcxy/cegove/notification-service/api;notificationb\x06proto3"

var (
	file_notification_service_proto_rawDescOnce sync.Once
	file_notification_service_proto_rawDescData []byte
)

func file_notification_service_proto_rawDescGZIP() []byte {
	file_notification_service_proto_rawDescOnce.Do(func() {
		file_notification_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_service_proto_rawDesc), len(file_notification_service_proto_rawDesc)))
	})
	return file_notification_service_proto_rawDescData
}

var file_notification_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_notification_service_proto_goTypes = []any{
	(*GetTemplateRequest)(nil),                 // 0: notification.GetTemplateRequest
	(*DeleteRequest)(nil),                      // 1: notification.DeleteRequest
	(*ListTemplatesResponse)(nil),              // 2: notification.ListTemplatesResponse
	(*ScheduleNotificationRequest)(nil),        // 3: notification.ScheduleNotificationRequest
	(*ListDueScheduledRequest)(nil),            // 4: notification.ListDueScheduledRequest
	(*ListScheduledNotificationsResponse)(nil), // 5: notification.ListScheduledNotificationsResponse
	(*MarkScheduledRequest)(nil),               // 6: notification.MarkScheduledRequest
	(*SendNotificationRequest)(nil),            // 7: notification.SendNotificationRequest
	(*SendNotificationResponse)(nil),           // 8: notification.SendNotificationResponse
	(*SendBatchNotificationRequest)(nil),       // 9: notification.SendBatchNotificationRequest
	(*SendBatchNotificationResponse)(nil),      // 10: notification.SendBatchNotificationResponse
	nil,                                        // 11: notification.ScheduleNotificationRequest.DynamicDataEntry
	(*NotificationTemplate)(nil),               // 12: notification.NotificationTemplate
	(*timestamppb.Timestamp)(nil),              // 13: google.protobuf.Timestamp
	(*ScheduledNotification)(nil),              // 14: notification.ScheduledNotification
	(*structpb.Value)(nil),                     // 15: google.protobuf.Value
	(*emptypb.Empty)(nil),                      // 16: google.protobuf.Empty
	(*SendSMSRequest)(nil),                     // 17: notification.SendSMSRequest
	(*SendSMSResponse)(nil),                    // 18: notification.SendSMSResponse
}
var file_notification_service_proto_depIdxs = []int32{
	12, // 0: notification.ListTemplatesResponse.templates:type_name -> notification.NotificationTemplate
	11, // 1: notification.ScheduleNotificationRequest.dynamic_data:type_name -> notification.ScheduleNotificationRequest.DynamicDataEntry
	13, // 2: notification.ScheduleNotificationRequest.schedule_at:type_name -> google.protobuf.Timestamp
	13, // 3: notification.ListDueScheduledRequest.now:type_name -> google.protobuf.Timestamp
	14, // 4: notification.ListScheduledNotificationsResponse.notifications:type_name -> notification.ScheduledNotification
	13, // 5: notification.MarkScheduledRequest.sent_at:type_name -> google.protobuf.Timestamp
	7,  // 6: notification.SendBatchNotificationRequest.notifications:type_name -> notification.SendNotificationRequest
	8,  // 7: notification.SendBatchNotificationResponse.results:type_name -> notification.SendNotificationResponse
	15, // 8: notification.ScheduleNotificationRequest.DynamicDataEntry.value:type_name -> google.protobuf.Value
	12, // 9: notification.NotificationService.CreateTemplate:input_type -> notification.NotificationTemplate
	0,  // 10: notification.NotificationService.GetTemplate:input_type -> notification.GetTemplateRequest
	16, // 11: notification.NotificationService.ListTemplates:input_type -> google.protobuf.Empty
	12, // 12: notification.NotificationService.UpdateTemplate:input_type -> notification.NotificationTemplate
	1,  // 13: notification.NotificationService.DeleteTemplate:input_type -> notification.DeleteRequest
	3,  // 14: notification.NotificationService.ScheduleNotification:input_type -> notification.ScheduleNotificationRequest
	4,  // 15: notification.NotificationService.ListDueScheduled:input_type -> notification.ListDueScheduledRequest
	6,  // 16: notification.NotificationService.MarkScheduledSent:input_type -> notification.MarkScheduledRequest
	7,  // 17: notification.NotificationService.SendNotification:input_type -> notification.SendNotificationRequest
	9,  // 18: notification.NotificationService.SendBatchNotification:input_type -> notification.SendBatchNotificationRequest
	17, // 19: notification.NotificationService.SendSMS:input_type -> notification.SendSMSRequest
	12, // 20: notification.NotificationService.CreateTemplate:output_type -> notification.NotificationTemplate
	12, // 21: notification.NotificationService.GetTemplate:output_type -> notification.NotificationTemplate
	2,  // 22: notification.NotificationService.ListTemplates:output_type -> notification.ListTemplatesResponse
	16, // 23: notification.NotificationService.UpdateTemplate:output_type -> google.protobuf.Empty
	16, // 24: notification.NotificationService.DeleteTemplate:output_type -> google.protobuf.Empty
	14, // 25: notification.NotificationService.ScheduleNotification:output_type -> notification.ScheduledNotification
	5,  // 26: notification.NotificationService.ListDueScheduled:output_type -> notification.ListScheduledNotificationsResponse
	16, // 27: notification.NotificationService.MarkScheduledSent:output_type -> google.protobuf.Empty
	8,  // 28: notification.NotificationService.SendNotification:output_type -> notification.SendNotificationResponse
	10, // 29: notification.NotificationService.SendBatchNotification:output_type -> notification.SendBatchNotificationResponse
	18, // 30: notification.NotificationService.SendSMS:output_type -> notification.SendSMSResponse
	20, // [20:31] is the sub-list for method output_type
	9,  // [9:20] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_notification_service_proto_init() }
func file_notification_service_proto_init() {
	if File_notification_service_proto != nil {
		return
	}
	file_notification_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_service_proto_rawDesc), len(file_notification_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_service_proto_goTypes,
		DependencyIndexes: file_notification_service_proto_depIdxs,
		MessageInfos:      file_notification_service_proto_msgTypes,
	}.Build()
	File_notification_service_proto = out.File
	file_notification_service_proto_goTypes = nil
	file_notification_service_proto_depIdxs = nil
}
